//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims_XML_Auto_Translator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims_XML_Auto_Translator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;sourceLanguage&quot;:{&quot;AT&quot;:&quot;Auto&quot;,&quot;CS&quot;:&quot;Čeština&quot;,&quot;DA&quot;:&quot;Dansk&quot;,&quot;DE&quot;:&quot;Deutsch&quot;,&quot;EN&quot;:&quot;English&quot;,&quot;ES&quot;:&quot;Español&quot;,&quot;FR&quot;:&quot;Français&quot;,&quot;IT&quot;:&quot;Italiano&quot;,&quot;NL&quot;:&quot;Nederlands&quot;,&quot;NB&quot;:&quot;Norsk&quot;,&quot;PL&quot;:&quot;Polski&quot;,&quot;PT&quot;:&quot;Português (Brasil)&quot;,&quot;FI&quot;:&quot;Suomi&quot;,&quot;SV&quot;:&quot;Svenska&quot;,&quot;RU&quot;:&quot;Русский&quot;,&quot;JA&quot;:&quot;日本語&quot;,&quot;ZH&quot;:&quot;简体中文&quot;,&quot;KO&quot;:&quot;한국어&quot;},&quot;targetLanguage&quot;:{&quot;CS&quot;:&quot;Čeština&quot;,&quot;DA&quot;:&quot;Dansk&quot;,&quot;DE&quot;:&quot;Deutsch&quot;,&quot;EN-US&quot;:&quot;English&quot;,&quot;ES&quot;:&quot;Español&quot;,&quot;FR&quot;:&quot;Français&quot;,&quot;IT&quot;:&quot;Italiano&quot;,&quot;NL&quot;:&quot;Nederlands&quot;,&quot;NB&quot;:&quot;Norsk&quot;,&quot;PL&quot;:&quo... ähnelt.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
    }
}
